### ISSUE TITLE
not mp safe

### ISSUE THREAD

**Issue by DeadlyKitten37** [Sil3ntStorm/factorio-explosive-trees#1]
this mod is not safe for multiplayer 

I had trouble reproducing it in a consistent manner but i think the issue is this line
![image](https://user-images.githubusercontent.com/53106272/168125113-ec7c8ec1-c648-4715-943a-71b6d529eedf.png)
anything saved from tick to tick MUST be saved in the right way or it will not be sent to new players as they join

**Comment by Sil3ntStorm** [comment]
I see, that makes sense. Should probably be stored in global, which should be synced by the game, which would guarantee that each player calculates the same thing locally.
Thanks for the report, will be fixed with the next update that I have been working on for a while (but haven't found the time to finish it as of late).
