### ISSUE TITLE
Balance?

### ISSUE THREAD

**Issue by DeadlyKitten37** [Sil3ntStorm/factorio-explosive-trees#2]
i am not sure if this is a bug or a feature but i found in testing that sometimes a would mine a tree and the entire forrest would go up in smoke.
![image](https://user-images.githubusercontent.com/53106272/168126065-df81b7bc-f4c2-4e31-a3b2-f67c3f9a95de.png)

I am not sure whay it dose this.

to reproduce-
load a new game
research all techs
set early game safety timer to 0
mine some trees, after mining a few the above happens

mod looks fun to use, just needs some kinks worked out first

**Comment by Sil3ntStorm** [comment]
Well, that's actually a desired effect for what I had in mind when creating it.
To disable that you would need to set the "Damage Trees explosion chance %" to 0, which would disable damaged trees causing further explosions. The higher that % setting, the higher the chance for entire forests to blow up. The unfortunate side effect however is that with turning that down you also don't get any effect from throwing grenades or poison caps on trees.
I would have to dig some more to see if you can actually tell if the grenade / poison was thrown down by a player in order to separate those.

In any case, if you don't want entire forests to go off, lower the damaged tree explosion chance.

**Comment by DeadlyKitten37** [comment]
please put in some documentation somewhere (most likely on the setting description) to inform the player this is the case. the net effect in game is not to make anything difficult or interesting, it just makes it hard to get wood and it is currently not obvious what setting causes this.
