### ISSUE TITLE
Setting requests

### ISSUE THREAD

**Issue by DeadlyKitten37** [Sil3ntStorm/factorio-explosive-trees#3]
ability to set chance for additional explosions to 0% chance of happening (why can you not already do this)
ability to set ticks between nukes much higher (gives you a break between cleaning up from nukes)
ability to set ticks between poison clouds much higher (same as above)
ability to set ticks between poison clouds lower (1 is just not dangerous)
remove the max early game safely time (why is it there)
for the description to include some useful info about max ticks in 1 min (most people do not know the conversion between ticks useful units of time)

mod looks fun, just needs some kinks worked out first

**Comment by Sil3ntStorm** [comment]
Poison and nukes have a limit because the game has absolutely horrendous (render) performance when there are more than 1-2 nukes going off at the same time, and the same is true for poison capsules although the number for those is somewhat higher compared to nukes.
During testing before I had the limits in, the sheer number of nukes and poison would just tank the game hard. I added the nuke delay and then poison turned out to have the same issue, so I just duplicated what I had for nukes.
The delay options for these will likely remain in ticks unless Factorio supports settings to be set in doubles (which I will check).

Early game safety time will retain a max value, because why shouldn't it have one? There is no challenge if you can just set it to 50 hours into the game before it starts doing stuff. I already have an update in the pipe, which has changed the setting from ticks to seconds. I have no idea why I did it in ticks, guess I quickly added that in last minute some night.

In any case the update that is pending completion, will add some more options, so I will adjust some of the existing ones.

Thanks for the feedback

**Comment by DeadlyKitten37** [comment]
in reverse order
-Early game safety time will retain a max value, because why shouldn't it have one?
It shouldn't have one because this small a mod should never force the player into what they want. there is not much challenge if you start it at 50 hours but that is not your place to decide. If someone does not want to deal with trees killing them early game they should have the ability to set it to 2 hours so the bots die not them

-The delay options for these will likely remain in ticks unless Factorio supports settings to be set in doubles 
https://wiki.factorio.com/Tutorial:Mod_settings#double-setting

-Max poison and nuke delay
The request for nukes was to allow a longer delay on poison and nukes. Currently the max delay between nukes is about 13 secs, it would be nice to only deal with a nuke every 30 - 120 mins

-min poison delay 
The current min poison delay is 1 sec. this is long enough that an entire forest will generate 1 poison cloud... that you can walk through and not care. allowing lower poison delay could make them more of a threat.
